
package Client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.1
 * Generated source version: 2.2
 * 
 */
@WebService(name = "GestionContactService", targetNamespace = "http://GestionContact/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface GestionContactService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteContact", targetNamespace = "http://GestionContact/", className = "Client.DeleteContact")
    @ResponseWrapper(localName = "deleteContactResponse", targetNamespace = "http://GestionContact/", className = "Client.DeleteContactResponse")
    @Action(input = "http://GestionContact/GestionContactService/deleteContactRequest", output = "http://GestionContact/GestionContactService/deleteContactResponse")
    public String deleteContact(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addContact", targetNamespace = "http://GestionContact/", className = "Client.AddContact")
    @ResponseWrapper(localName = "addContactResponse", targetNamespace = "http://GestionContact/", className = "Client.AddContactResponse")
    @Action(input = "http://GestionContact/GestionContactService/addContactRequest", output = "http://GestionContact/GestionContactService/addContactResponse")
    public String addContact(
        @WebParam(name = "arg0", targetNamespace = "")
        Contact arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns Client.Contact
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getContact", targetNamespace = "http://GestionContact/", className = "Client.GetContact")
    @ResponseWrapper(localName = "getContactResponse", targetNamespace = "http://GestionContact/", className = "Client.GetContactResponse")
    @Action(input = "http://GestionContact/GestionContactService/getContactRequest", output = "http://GestionContact/GestionContactService/getContactResponse")
    public Contact getContact(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateContact", targetNamespace = "http://GestionContact/", className = "Client.UpdateContact")
    @ResponseWrapper(localName = "updateContactResponse", targetNamespace = "http://GestionContact/", className = "Client.UpdateContactResponse")
    @Action(input = "http://GestionContact/GestionContactService/updateContactRequest", output = "http://GestionContact/GestionContactService/updateContactResponse")
    public String updateContact(
        @WebParam(name = "arg0", targetNamespace = "")
        Contact arg0);

}
